# Generated by Django 4.2.3 on 2023-07-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_id_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='dvd',
        ),
    ]
